logo: # add logo name
title: Cari's Data Science Blog
description: > # this means to ignore newlines until "baseurl:"
  This is a blog I've created in a theme called Bef.
permalink: ':title/'
baseurl: "/cgostic_bef_theme" # the subpath of your site, e.g. /blog
url: "https://cgostic.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: BirchLeaves.jpg # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic:  author.jpg # your photo
author-name: 'Cari Gostic' # your name
about-author: 'I like data science very much!' # about author
email: cari.gostic@gmail.com # your email
phone:  (236) 979-8363 # your pnone number
#website:  # your website

# Social link
google_url:    # add url link
# twitter_url:   # add url link
# instagram_url: # add url link
# pinterest_url: # add url link
# dribbble_url:  # add url link
# facebook_url:  # add url link
linkedin_url: https://www.linkedin.com/in/cari-gostic-b93588121/

# Disqus
# discus_identifier: #cgostic # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: #https://disqus.com/admin/create/

# Newsletter
# mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
# analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
